/** Sip & Spill — prompt deck */
window.SIP_PROMPTS = [
  { id: "m01", category: "mild", text: "What's the most embarrassing song you'd still belt at karaoke after three drinks?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks — then hums 5 seconds." },
  { id: "m02", category: "mild", text: "Who in this room would die first in a horror movie because they 'went to check the noise'?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks for the plot armor deficit." },
  { id: "m03", category: "mild", text: "Confess your most unhinged Google search from this month.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip if you refuse. Extra sip if it involved WebMD." },
  { id: "m04", category: "mild", text: "What's a skill you list on your résumé that is… aspirational?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Drink if someone calls you out." },
  { id: "m05", category: "mild", text: "Who here would make the worst roommate — laundry crimes, fridge science, or both?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks. Defense optional." },
  { id: "m06", category: "mild", text: "What's the pettiest reason you've ever left someone on read?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Take a sip for the villain era." },
  { id: "m07", category: "mild", text: "Name a celebrity you'd switch lives with for a week — knowing you'd ruin their brand in 48 hours.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Everyone who disagrees drinks." },
  { id: "m08", category: "mild", text: "What's your most-used emoji, and what crime against personality does it reveal?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip after answering." },
  { id: "m09", category: "mild", text: "Who in this group has a car that looks like a moving dumpster fire?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks. Keys stay hidden." },
  { id: "m10", category: "mild", text: "What's a hill you'll die on that makes everyone side-eye you?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Defend it or drink twice." },
  { id: "m11", category: "mild", text: "Describe your dating profile in three words — no filter, no mercy.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Group votes; if they laugh, you drink." },
  { id: "m12", category: "mild", text: "What's the worst fashion choice you've ever committed in public?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip for the shame archives." },
  { id: "m13", category: "mild", text: "Who here texts like they just discovered capital letters in 2014?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks." },
  { id: "m14", category: "mild", text: "What's something you still can't do as an adult that a 12-year-old YouTuber can?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Everyone who also can't does a sip." },
  { id: "m15", category: "mild", text: "Rate your last hangover 1–10. Be dramatic.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Drink that many sips (max 5)." },
  { id: "m16", category: "mild", text: "Who would you want on your bar trivia team — and who would you bench?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Benched person drinks." },
  { id: "m17", category: "mild", text: "What's a rumor about you that was annoyingly accurate?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip if you have none (suspicious)." },
  { id: "m18", category: "mild", text: "Name your most controversial food opinion. Pineapple discourse encouraged.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Haters drink." },
  { id: "m19", category: "mild", text: "Who in this room has the most Olympic-level excuses for being late?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks for the track record." },
  { id: "m20", category: "mild", text: "What's the longest you've gone without showering on vacation — be honest?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip if over 2 days. Hydrate either way." },
  { id: "m21", category: "mild", text: "If your life had a theme song right now, what tragic bop is it?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Play it or drink." },
  { id: "m22", category: "mild", text: "Who here would cry first at a talking dog commercial?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks (proudly)." },
  { id: "m23", category: "mild", text: "Admit a white lie you told this week. We already know.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip after the confession." },
  { id: "m24", category: "mild", text: "What's your go-to karaoke song when you have zero vocal credentials?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Hum it or drink twice." },
  { id: "m25", category: "mild", text: "If you had to delete one app forever, which one would make you spiral?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip for the addiction." },
  { id: "m26", category: "mild", text: "What's a compliment you got that you still replay like a trailer?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Everyone drinks to good vibes." },
  { id: "m27", category: "mild", text: "Who would win a staring contest — and who would blink because they remembered taxes?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Loser of a quick stare drinks." },
  { id: "m28", category: "mild", text: "Who here spends the most on coffee like it's a personality?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks (ironic caffeine tax)." },
  { id: "m29", category: "mild", text: "What's a movie you pretend you've seen so people stop explaining it?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip if caught." },
  { id: "m30", category: "mild", text: "Describe your type in one sentence — no PR team.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Friends roast; you drink if they roast well." },
  { id: "m31", category: "mild", text: "Who is most likely to get lost using GPS with confidence?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks." },
  { id: "m32", category: "mild", text: "What's the weirdest thing in your camera roll that isn't a meme?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Show or drink." },
  { id: "m33", category: "mild", text: "Name a TV show you're embarrassed to still love like it's 2012.", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip for the nostalgia." },
  { id: "m34", category: "mild", text: "Who here has the strongest, least-negotiable pizza topping opinions?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks, then lectures." },
  { id: "m35", category: "mild", text: "What's something you bought and regretted before the package even arrived?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Everyone who relates sips." },
  { id: "m36", category: "mild", text: "Who would survive a group project by contributing vibes only?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks." },
  { id: "m37", category: "mild", text: "What's your most pathetic 'I'm fine' moment this year?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip after sharing." },
  { id: "m38", category: "mild", text: "If your browser history were a Netflix genre, what would it be called?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Group titles it; you drink if it's accurate." },
  { id: "m39", category: "mild", text: "Who here would start a cult by accident because they're too persuasive?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks. No recruitment." },
  { id: "m40", category: "mild", text: "What's the dumbest hill you've argued on in a group chat?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Sip for the digital warfare." },
  { id: "m41", category: "mild", text: "Rate your cooking from 'fine dining' to 'fire department on speed dial.'", hint: "Truth — answer honestly, then follow the sip rule.", rule: "Drink if under 'edible.'" },
  { id: "m42", category: "mild", text: "Who would forget their own birthday if we didn't remind them?", hint: "Truth — answer honestly, then follow the sip rule.", rule: "That person drinks." },
  { id: "s01", category: "spicy", text: "What's the riskiest place you've actually fucked — not just made out?", hint: "Spicy truth — keep it dirty or drink.", rule: "Drink if you won't say. Details get a group sip." },
  { id: "s02", category: "spicy", text: "Who in this room would you most want to fuck on a dare? Point.", hint: "Spicy truth — keep it dirty or drink.", rule: "Point or drink twice. Be adults." },
  { id: "s03", category: "spicy", text: "Describe your worst sexual encounter — leave the awkward parts in.", hint: "Spicy truth — keep it dirty or drink.", rule: "Take a sip mid-story." },
  { id: "s04", category: "spicy", text: "Have you ever sent a filthy text to the wrong person? Spill the fallout.", hint: "Spicy truth — keep it dirty or drink.", rule: "Confess or drink." },
  { id: "s05", category: "spicy", text: "What's your biggest turn-on that you'd never put in a dating bio?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip after sharing. Keep it adult." },
  { id: "s06", category: "spicy", text: "Rate your dirty-talk game 1–10. Friends may veto.", hint: "Spicy truth — keep it dirty or drink.", rule: "Drink the difference from 10." },
  { id: "s07", category: "spicy", text: "Who here has the filthiest dating history? Make them prove it.", hint: "Spicy truth — keep it dirty or drink.", rule: "That person drinks — then spills one tea." },
  { id: "s08", category: "spicy", text: "Ever been caught mid-hookup or mid-solo session? Story time.", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip for courage." },
  { id: "s09", category: "spicy", text: "What's a sexual fantasy you'd only admit after two drinks?", hint: "Spicy truth — keep it dirty or drink.", rule: "You're past two. Answer or drink thrice." },
  { id: "s10", category: "spicy", text: "What's the most awkward thing you've said during sex?", hint: "Spicy truth — keep it dirty or drink.", rule: "Drink if you freeze." },
  { id: "s11", category: "spicy", text: "Name a celebrity you'd actually try to fuck IRL — no PR answers.", hint: "Spicy truth — keep it dirty or drink.", rule: "Haters drink." },
  { id: "s12", category: "spicy", text: "Have you ever had friends-with-benefits that got messy? How messy?", hint: "Spicy truth — keep it dirty or drink.", rule: "Story or two sips." },
  { id: "s13", category: "spicy", text: "Who in this group is the biggest tease / flirt?", hint: "Spicy truth — keep it dirty or drink.", rule: "That person drinks." },
  { id: "s14", category: "spicy", text: "What's a dealbreaker in bed you learned the hard (or soft) way?", hint: "Spicy truth — keep it dirty or drink.", rule: "Share or drink." },
  { id: "s15", category: "spicy", text: "What's the hottest / dirtiest text you've ever received? Read a sanitized version aloud.", hint: "Spicy truth — keep it dirty or drink.", rule: "Read it or drink twice." },
  { id: "s16", category: "spicy", text: "Ever had a crush on a friend's ex you'd still hook up with?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes — no judgment, just chaos." },
  { id: "s17", category: "spicy", text: "What's something filthy on your sexual bucket list?", hint: "Spicy truth — keep it dirty or drink.", rule: "Share or three sips." },
  { id: "s18", category: "spicy", text: "What's your most regrettable drunk hookup decision?", hint: "Spicy truth — keep it dirty or drink.", rule: "Confess or drink." },
  { id: "s19", category: "spicy", text: "Spill your most shameless thirst-trap or nudes-adjacent moment.", hint: "Spicy truth — keep it dirty or drink.", rule: "Show SFW proof or drink." },
  { id: "s20", category: "spicy", text: "If this party ended in a makeout-or-more dare, who starts it?", hint: "Spicy truth — keep it dirty or drink.", rule: "Point fingers; pointed people drink." },
  { id: "s21", category: "spicy", text: "Have you ever catfished / roleplayed online for sexual fun?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes." },
  { id: "s22", category: "spicy", text: "Who would last longest on a filthy reality dating show?", hint: "Spicy truth — keep it dirty or drink.", rule: "Everyone else drinks." },
  { id: "s23", category: "spicy", text: "Body count ballpark — range only. No shame, just math.", hint: "Spicy truth — keep it dirty or drink.", rule: "Pass = drink. Answer = everyone else sips." },
  { id: "s24", category: "spicy", text: "Describe your ideal one-night stand in one filthy sentence.", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip after." },
  { id: "s25", category: "spicy", text: "Ever been on a dating app while technically taken?", hint: "Spicy truth — keep it dirty or drink.", rule: "Honesty sip either way." },
  { id: "s26", category: "spicy", text: "Who here would be the best kisser — and who would be best in bed? Two votes.", hint: "Spicy truth — keep it dirty or drink.", rule: "Winners drink; losers drink too." },
  { id: "s27", category: "spicy", text: "Have you ever walked in on sex — or been walked in on?", hint: "Spicy truth — keep it dirty or drink.", rule: "Story + sip." },
  { id: "s28", category: "spicy", text: "Rate this group's collective fuckability / rizz. Be brutal.", hint: "Spicy truth — keep it dirty or drink.", rule: "Everyone drinks for the score out of 5." },
  { id: "s29", category: "spicy", text: "Who would you least want to see naked in this room? (Be kind-ish.)", hint: "Spicy truth — keep it dirty or drink.", rule: "Drink for the awkwardness." },
  { id: "s30", category: "spicy", text: "Have you ever faked being busy to dodge a hookup?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes." },
  { id: "s31", category: "spicy", text: "Strip Truth: remove one accessory / outer layer or take two drinks.", hint: "Spicy truth — keep it dirty or drink.", rule: "Choose wisely. Consent for any help." },
  { id: "s32", category: "spicy", text: "Who here has the most scandalous porn / search history?", hint: "Spicy truth — keep it dirty or drink.", rule: "That person drinks." },
  { id: "s33", category: "spicy", text: "Describe your last hookup in three adjectives — no soft-pedaling.", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if it was awkward." },
  { id: "s34", category: "spicy", text: "Have you ever been someone's rebound fuck — or used one?", hint: "Spicy truth — keep it dirty or drink.", rule: "Honesty drinks all around." },
  { id: "s35", category: "spicy", text: "What's a compliment that always gets you wet / hard?", hint: "Spicy truth — keep it dirty or drink.", rule: "Everyone tries; you drink if none land." },
  { id: "s36", category: "spicy", text: "Would you rather: insane chemistry + terrible personality, or the reverse?", hint: "Spicy truth — keep it dirty or drink.", rule: "Defend pick; dissenters drink." },
  { id: "s37", category: "spicy", text: "Who in this room has 'I'd ruin my sleep schedule for them' energy?", hint: "Spicy truth — keep it dirty or drink.", rule: "That person drinks." },
  { id: "s38", category: "spicy", text: "Ever sexted and immediately regretted the typos / autocorrect?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes." },
  { id: "s39", category: "spicy", text: "What's your most out-of-line spicy opinion about sex or dating?", hint: "Spicy truth — keep it dirty or drink.", rule: "Group reacts; you drink if roasted." },
  { id: "s40", category: "spicy", text: "Truth or sip: last person you fantasized about fucking — initials only.", hint: "Spicy truth — keep it dirty or drink.", rule: "Drink to pass." },
  { id: "s41", category: "spicy", text: "Have you ever had sex in someone else's bed (guest room chaos)?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes. Story optional." },
  { id: "s42", category: "spicy", text: "What's your favorite position — and why does it win?", hint: "Spicy truth — keep it dirty or drink.", rule: "Share or drink twice." },
  { id: "s43", category: "spicy", text: "Ever recorded yourself / a partner (consensual) and panicked later?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes. No sharing media here." },
  { id: "s44", category: "spicy", text: "Who here would be down for a threesome if the stars aligned?", hint: "Spicy truth — keep it dirty or drink.", rule: "Pointers drink; pointed people sip." },
  { id: "s45", category: "spicy", text: "What's the filthiest nickname you've used or been called in bed?", hint: "Spicy truth — keep it dirty or drink.", rule: "Say it or drink." },
  { id: "s46", category: "spicy", text: "Have you ever hooked up with someone from work / class and kept it secret?", hint: "Spicy truth — keep it dirty or drink.", rule: "Confess or two sips." },
  { id: "s47", category: "spicy", text: "Rate your oral skills 1–10. Ego check welcome.", hint: "Spicy truth — keep it dirty or drink.", rule: "Drink the gap from 10 if friends veto." },
  { id: "s48", category: "spicy", text: "What's a kink you're curious about but haven't tried yet?", hint: "Spicy truth — keep it dirty or drink.", rule: "Share or three sips." },
  { id: "s49", category: "spicy", text: "Ever finished too fast and had to… creatively recover?", hint: "Spicy truth — keep it dirty or drink.", rule: "Sip if yes. Solidarity sips allowed." },
  { id: "s50", category: "spicy", text: "Who would you pick for a no-strings weekend away from this room?", hint: "Spicy truth — keep it dirty or drink.", rule: "Point or drink twice." },
  { id: "c01", category: "chaos", text: "Everyone drinks if you've ever peed in a pool.", hint: "Chaos — do the dare / follow the group rule.", rule: "No exceptions." },
  { id: "c02", category: "chaos", text: "Dare: speak in an accent until your next turn — or drink twice.", hint: "Chaos — do the dare / follow the group rule.", rule: "Group enforces." },
  { id: "c03", category: "chaos", text: "Everyone with a cracked phone screen: drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "Show your screen." },
  { id: "c04", category: "chaos", text: "Last person to touch the ceiling drinks. Go!", hint: "Chaos — do the dare / follow the group rule.", rule: "No furniture stacking." },
  { id: "c05", category: "chaos", text: "Everyone drinks if you've cried at a party before.", hint: "Chaos — do the dare / follow the group rule.", rule: "It's okay." },
  { id: "c06", category: "chaos", text: "Dare: swap seats with someone across the room — or sip twice.", hint: "Chaos — do the dare / follow the group rule.", rule: "Chaos encouraged." },
  { id: "c07", category: "chaos", text: "Anyone wearing black: drink. Anyone not: also drink. Gotcha.", hint: "Chaos — do the dare / follow the group rule.", rule: "Sip sip." },
  { id: "c08", category: "chaos", text: "Rock-paper-scissors with your left neighbor. Loser drinks.", hint: "Chaos — do the dare / follow the group rule.", rule: "Best of one." },
  { id: "c09", category: "chaos", text: "Everyone drinks if your bank account is under $100 right now.", hint: "Chaos — do the dare / follow the group rule.", rule: "Don't check — just feel it." },
  { id: "c10", category: "chaos", text: "Dare: post a blurry story saying 'living my best life' — or drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "Proof required." },
  { id: "c11", category: "chaos", text: "Tallest person drinks. Shortest person also drinks. Equality.", hint: "Chaos — do the dare / follow the group rule.", rule: "Stand up." },
  { id: "c12", category: "chaos", text: "Everyone who checked their phone in the last 5 minutes: drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "Honor system." },
  { id: "c13", category: "chaos", text: "Dare: do your best dance move for 10 seconds — or two sips.", hint: "Chaos — do the dare / follow the group rule.", rule: "Phone camera optional." },
  { id: "c14", category: "chaos", text: "Waterfall! Start left of the phone-holder.", hint: "Chaos — do the dare / follow the group rule.", rule: "No stopping until the person before you stops." },
  { id: "c15", category: "chaos", text: "Dare: call your most recent contact and say 'I love your energy' — or drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "Speakers on." },
  { id: "c16", category: "chaos", text: "Categories: name drink brands until someone fails. Loser drinks.", hint: "Chaos — do the dare / follow the group rule.", rule: "No repeats." },
  { id: "c17", category: "chaos", text: "Floor is lava for 15 seconds. Last feet down drinks.", hint: "Chaos — do the dare / follow the group rule.", rule: "Couch is safe." },
  { id: "c18", category: "chaos", text: "Anyone who has ghosted a group chat this month: drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "You know who you are." },
  { id: "c19", category: "chaos", text: "Dare: wear your shirt inside out until next chaos card — or drink twice.", hint: "Chaos — do the dare / follow the group rule.", rule: "Commit." },
  { id: "c20", category: "chaos", text: "Rhyming toast: make a toast that rhymes or finish your drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "Group cheers either way." },
  { id: "c21", category: "chaos", text: "Everyone drinks if you've ever thrown up in an Uber / Lyft.", hint: "Chaos — do the dare / follow the group rule.", rule: "Tip well next time." },
  { id: "c22", category: "chaos", text: "Thumb war tournament: pair up. Losers drink.", hint: "Chaos — do the dare / follow the group rule.", rule: "Final loser drinks twice." },
  { id: "c23", category: "chaos", text: "Dare: speak only in questions until your next turn — or sip twice.", hint: "Chaos — do the dare / follow the group rule.", rule: "Are you ready?" },
  { id: "c24", category: "chaos", text: "Group photo NOW. Last person in frame drinks.", hint: "Chaos — do the dare / follow the group rule.", rule: "Make it ugly on purpose." },
  { id: "c25", category: "chaos", text: "Dare: balance your drink on your head for 5 seconds — spill = finish it.", hint: "Chaos — do the dare / follow the group rule.", rule: "Steady hands." },
  { id: "c26", category: "chaos", text: "People born in odd months drink. Even months: you're next round.", hint: "Chaos — do the dare / follow the group rule.", rule: "Remember." },
  { id: "c27", category: "chaos", text: "Everyone drinks if you've ever stolen a street sign / cone.", hint: "Chaos — do the dare / follow the group rule.", rule: "Icons only." },
  { id: "c28", category: "chaos", text: "Dare: let the group rewrite your lock-screen text for 10 min — or drink thrice.", hint: "Chaos — do the dare / follow the group rule.", rule: "Be brave." },
  { id: "c29", category: "chaos", text: "Anyone single: drink. Anyone taken: drink to your person. It's a trap.", hint: "Chaos — do the dare / follow the group rule.", rule: "Cheers." },
  { id: "c30", category: "chaos", text: "Last person to say their middle name drinks.", hint: "Chaos — do the dare / follow the group rule.", rule: "Go!" },
  { id: "c31", category: "chaos", text: "Everyone who has ever blacked out: take a respectful sip.", hint: "Chaos — do the dare / follow the group rule.", rule: "Hydrate too." },
  { id: "c32", category: "chaos", text: "Everyone with unread emails over 50: drink for each 50 (max 3).", hint: "Chaos — do the dare / follow the group rule.", rule: "Inbox zero warriors: sip once for smugness." },
  { id: "c33", category: "chaos", text: "Left-handed people drink. Right-handed: clap for them then drink anyway.", hint: "Chaos — do the dare / follow the group rule.", rule: "Ambidextrous: choose your fighter sip." },
  { id: "c34", category: "chaos", text: "Everyone who has a nickname they hate: drink when someone uses it.", hint: "Chaos — do the dare / follow the group rule.", rule: "Use them liberally." },
  { id: "c35", category: "chaos", text: "Never have I ever… host picks one. Drinkers drink. Passers cheer.", hint: "Chaos — do the dare / follow the group rule.", rule: "Keep it party-safe." },
  { id: "st01", category: "sexy_truth", text: "What's the sexiest thing you've ever worn with the sole intent of getting someone out of theirs?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Describe it or sip twice." },
  { id: "st02", category: "sexy_truth", text: "Where's the dirtiest / strangest place you've had sex or serious oral?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Spill or drink." },
  { id: "st03", category: "sexy_truth", text: "What's your favorite kind of kiss — soft, rough, neck, or lower?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip after answering." },
  { id: "st04", category: "sexy_truth", text: "Have you ever had a one-night stand you still masturbate thinking about?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Honesty sip either way." },
  { id: "st05", category: "sexy_truth", text: "What's a bedroom compliment that ruins you in the best way?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Share or drink." },
  { id: "st06", category: "sexy_truth", text: "Rate your dirty-talk game 1–10 — give an example line.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Friends may adjust; drink the gap from 10." },
  { id: "st07", category: "sexy_truth", text: "What's your biggest 'don't knock it till you try it' sexual preference?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip if you pass." },
  { id: "st08", category: "sexy_truth", text: "Ever been caught mid-fuck or mid-oral? Story, keep names optional.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip for courage." },
  { id: "st09", category: "sexy_truth", text: "What's the longest dry spell you've survived as an adult?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Everyone under that number sips." },
  { id: "st10", category: "sexy_truth", text: "Lights on, lights off, or blindfold? Defend your pick.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Dissenters drink." },
  { id: "st11", category: "sexy_truth", text: "What's a fantasy you've never told a partner out loud?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Answer or three sips." },
  { id: "st12", category: "sexy_truth", text: "Have you ever sent nudes and instantly panicked — or loved the power?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip if panic. Double sip if power trip." },
  { id: "st13", category: "sexy_truth", text: "Who here gives 'I'd ruin my life / sleep for them' sexual energy?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "That person drinks." },
  { id: "st14", category: "sexy_truth", text: "What's your go-to move when you want someone to know you want to fuck?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Demo verbally or drink." },
  { id: "st15", category: "sexy_truth", text: "Ever hooked up with someone from this friend circle's orbit?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Confess or drink twice." },
  { id: "st16", category: "sexy_truth", text: "What's the hottest non-sexual thing someone can do that still turns you on?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip after." },
  { id: "st17", category: "sexy_truth", text: "Describe your ideal lazy morning sex — positions optional, honesty mandatory.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip after. Keep it adult." },
  { id: "st18", category: "sexy_truth", text: "Have you ever faked an orgasm? Be real.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip if yes — no shame." },
  { id: "st19", category: "sexy_truth", text: "What's a turn-off that kills the night immediately?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Share or drink." },
  { id: "st20", category: "sexy_truth", text: "Truth: last person you had a filthy dream about — first initial only.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Pass = drink." },
  { id: "st21", category: "sexy_truth", text: "Would you rather: amazing kisser / mid in bed, or mid kisser / god-tier in bed?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Defend; haters drink." },
  { id: "st22", category: "sexy_truth", text: "What's something you're filthy-good at that surprises partners?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Brag or sip." },
  { id: "st23", category: "sexy_truth", text: "Ever had a vacation fling? Spill the spicy details (no doxxing).", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Story or two drinks." },
  { id: "st24", category: "sexy_truth", text: "What's your love language when things get physical — talk, touch, pace, praise?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip after answering." },
  { id: "st25", category: "sexy_truth", text: "If you had a free pass for one celebrity, who are you fucking?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Group roasts; you sip if they roast well." },
  { id: "st26", category: "sexy_truth", text: "Do you prefer to be in control in bed, or thoroughly taken care of?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Defend; sip after." },
  { id: "st27", category: "sexy_truth", text: "What's the most embarrassing place you've gotten off alone?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Share or drink twice." },
  { id: "st28", category: "sexy_truth", text: "Have you ever had sex while someone else was in the house / next room?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip if yes." },
  { id: "st29", category: "sexy_truth", text: "What's your favorite type of foreplay — and how long should it last?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Share or drink." },
  { id: "st30", category: "sexy_truth", text: "Ever used food / ice / toys in bed? Which worked?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Spill or three sips." },
  { id: "st31", category: "sexy_truth", text: "What's a word / phrase that instantly turns you on?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Say it or drink." },
  { id: "st32", category: "sexy_truth", text: "Have you ever squirmed through a public makeout that almost went further?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip if yes." },
  { id: "st33", category: "sexy_truth", text: "Rate morning sex vs. drunk sex vs. angry makeup sex.", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Pick a winner; dissenters drink." },
  { id: "st34", category: "sexy_truth", text: "What's the risque-est photo / video on your phone right now (don't show)?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Describe the vibe or drink." },
  { id: "st35", category: "sexy_truth", text: "Ever had a partner watch you touch yourself — or vice versa?", hint: "Sexy Truth — spill the filthy tea or sip to pass.", rule: "Sip if yes." },
  { id: "sd01", category: "sexy_dare", text: "Dare: give a consenting person a 10-second shoulder/neck massage — or drink twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Ask first. No = they drink instead; you still may sip." },
  { id: "sd02", category: "sexy_dare", text: "Dare: whisper the filthiest pickup line you know into someone's ear (consent) — or sip twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "They choose who. Refuse = drink." },
  { id: "sd03", category: "sexy_dare", text: "Dare: slow-dance pressed close with someone for 20 seconds — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Both must agree. Music optional." },
  { id: "sd04", category: "sexy_dare", text: "Dare: hold eye contact and bite your lip for 10 seconds while the group rates you — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Do it or sip twice." },
  { id: "sd05", category: "sexy_dare", text: "Dare: sit on a consenting person's lap for the next round — or two sips.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Both people must agree. Either can refuse = drink." },
  { id: "sd06", category: "sexy_dare", text: "Dare: describe how you'd seduce someone using only song titles — keep it dirty — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Group guesses the songs." },
  { id: "sd07", category: "sexy_dare", text: "Dare: give a fake Oscar speech about your hottest hookup (no names) — or drink twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Under 20 seconds." },
  { id: "sd08", category: "sexy_dare", text: "Dare: hold eye contact with someone for 15 seconds without laughing — or sip.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Both consent. Loser of the stare drinks." },
  { id: "sd09", category: "sexy_dare", text: "Dare: let someone write a one-word spicy compliment on your hand — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Consent for writer + canvas. Keep it until the game ends." },
  { id: "sd10", category: "sexy_dare", text: "Dare: send a voice note saying something flirty to a contact you choose — or drink thrice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Show proof of send. Keep it adult & non-harassing." },
  { id: "sd11", category: "sexy_dare", text: "Dare: demonstrate your best 'I want you' look — or two sips.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Group votes; low score = extra sip." },
  { id: "sd12", category: "sexy_dare", text: "Dare: trade a clothing accessory with someone for 3 rounds — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Consent required. Refuse = drink." },
  { id: "sd13", category: "sexy_dare", text: "Dare: compliment three people on something hot / non-obvious — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "No 'nice shirt' cop-outs." },
  { id: "sd14", category: "sexy_dare", text: "Dare: recreate your first-date 'I'd kiss you' body language for 10 seconds — or sip twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Commit to the bit." },
  { id: "sd15", category: "sexy_dare", text: "Dare: let the group pick a flirty Instagram story caption (keep it non-doxxing) — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Post or sip thrice." },
  { id: "sd16", category: "sexy_dare", text: "Dare: give a consenting person a forehead or cheek kiss — or finish half your drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "No means no = they drink instead; you drink too if you pushed." },
  { id: "sd17", category: "sexy_dare", text: "Dare: rank the three most attractive traits in the room out loud — or drink twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Be kind, be spicy. No body-shaming." },
  { id: "sd18", category: "sexy_dare", text: "Dare: play 30 seconds of spicy 'would you rather' with your neighbor.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Loser of each pick sips. Either can bail = drink." },
  { id: "sd19", category: "sexy_dare", text: "Dare: read a spicy text (real or typed now) in a movie-trailer voice — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Keep it consensual & adult. No non-consensual content." },
  { id: "sd20", category: "sexy_dare", text: "Dare: let someone style your hair / collar for the next two cards — or sip twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Consent first." },
  { id: "sd21", category: "sexy_dare", text: "Dare: whisper a secret turn-on to the person on your left — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "They announce a one-word review (SFW)." },
  { id: "sd22", category: "sexy_dare", text: "Dare: start a group hug lasting 5 seconds — or everyone sips.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Anyone can step out without penalty drink." },
  { id: "sd23", category: "sexy_dare", text: "Dare: remove one accessory (watch, socks, jewelry) for 3 rounds — or drink twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Clothes stay on unless you choose otherwise. Refuse = drink." },
  { id: "sd24", category: "sexy_dare", text: "Dare: trace a heart on a consenting person's palm with your finger — or sip twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Ask first. Refuse = drink." },
  { id: "sd25", category: "sexy_dare", text: "Dare: say your favorite body part on yourself and why — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Keep it confident, not cruel to others." },
  { id: "sd26", category: "sexy_dare", text: "Dare: let the group assign you a temporary flirty nickname — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Use it for 3 rounds. Cruel names vetoed." },
  { id: "sd27", category: "sexy_dare", text: "Dare: give a 5-second 'movie almost-kiss' lean-in to a consenting partner/friend — or drink thrice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Both must agree. No contact required if either balks — drink instead." },
  { id: "sd28", category: "sexy_dare", text: "Dare: demonstrate how you'd ask for consent in the sexiest voice you can — or two sips.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Group rates 1–10; under 6 = extra sip." },
  { id: "sd29", category: "sexy_dare", text: "Dare: swap seats so you're next to your secret (or not-so-secret) crush energy — or drink.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "No outing people cruelly. Refuse = drink." },
  { id: "sd30", category: "sexy_dare", text: "Dare: take a sexy (SFW) mirror selfie pose for 5 seconds — delete after — or drink twice.", hint: "Sexy Dare — do it (consensual) or drink. Refuse = drink.", rule: "Group may not snatch the phone." },
  { id: "nh01", category: "never_have_i_ever", text: "Never have I ever lied about my age.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh02", category: "never_have_i_ever", text: "Never have I ever ghosted someone after a great date.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh03", category: "never_have_i_ever", text: "Never have I ever pretended to know a song's lyrics.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh04", category: "never_have_i_ever", text: "Never have I ever stalked an ex on social media this year.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh05", category: "never_have_i_ever", text: "Never have I ever kissed more than one person in the same night.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh06", category: "never_have_i_ever", text: "Never have I ever sent a risky / dirty text and then muted the chat.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh07", category: "never_have_i_ever", text: "Never have I ever been kicked out of a bar or club.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh08", category: "never_have_i_ever", text: "Never have I ever said 'I love you' too early.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh09", category: "never_have_i_ever", text: "Never have I ever had sex in a car.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh10", category: "never_have_i_ever", text: "Never have I ever used a fake name at a party.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh11", category: "never_have_i_ever", text: "Never have I ever stolen food from a roommate.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh12", category: "never_have_i_ever", text: "Never have I ever peed outside as an adult.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh13", category: "never_have_i_ever", text: "Never have I ever flirted to get free drinks.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh14", category: "never_have_i_ever", text: "Never have I ever gone home with someone whose name I forgot.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh15", category: "never_have_i_ever", text: "Never have I ever cried during an argument I started.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh16", category: "never_have_i_ever", text: "Never have I ever double-texted after being left on read.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh17", category: "never_have_i_ever", text: "Never have I ever had a secret crush on a friend's partner.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh18", category: "never_have_i_ever", text: "Never have I ever lied about being busy to cancel plans.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh19", category: "never_have_i_ever", text: "Never have I ever danced on a table / bar.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh20", category: "never_have_i_ever", text: "Never have I ever worn the same underwear two days in a row.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh21", category: "never_have_i_ever", text: "Never have I ever snooped through someone's phone.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh22", category: "never_have_i_ever", text: "Never have I ever had a friends-with-benefits arrangement.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh23", category: "never_have_i_ever", text: "Never have I ever joined the mile-high club… or seriously planned it.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if either." },
  { id: "nh24", category: "never_have_i_ever", text: "Never have I ever been in love with two people at once.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh25", category: "never_have_i_ever", text: "Never have I ever regretted a tattoo or piercing.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh26", category: "never_have_i_ever", text: "Never have I ever sent nudes.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh27", category: "never_have_i_ever", text: "Never have I ever had a one-night stand.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh28", category: "never_have_i_ever", text: "Never have I ever had sex in a public-ish place (risk of getting caught).", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh29", category: "never_have_i_ever", text: "Never have I ever faked an orgasm.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh30", category: "never_have_i_ever", text: "Never have I ever used a sex toy with a partner.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh31", category: "never_have_i_ever", text: "Never have I ever had a threesome (or a very serious almost).", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if either." },
  { id: "nh32", category: "never_have_i_ever", text: "Never have I ever filmed a consensual sex tape / spicy video.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have. No sharing." },
  { id: "nh33", category: "never_have_i_ever", text: "Never have I ever hooked up with someone from a dating app the same day we matched.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh34", category: "never_have_i_ever", text: "Never have I ever had phone sex or video sex.", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "nh35", category: "never_have_i_ever", text: "Never have I ever roleplayed in bed (costumes optional).", hint: "Never Have I Ever — drink if you HAVE done it.", rule: "Drink if you have." },
  { id: "ml01", category: "most_likely", text: "Who is most likely to start a karaoke night unprompted?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml02", category: "most_likely", text: "Who is most likely to get married first?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml03", category: "most_likely", text: "Who is most likely to get lost on the way here?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml04", category: "most_likely", text: "Who is most likely to cry at a wedding toast?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml05", category: "most_likely", text: "Who is most likely to survive on delivery food alone?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml06", category: "most_likely", text: "Who is most likely to become famous for something chaotic?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml07", category: "most_likely", text: "Who is most likely to forget their own birthday plans?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml08", category: "most_likely", text: "Who is most likely to text their ex after two drinks?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml09", category: "most_likely", text: "Who is most likely to own too many houseplants?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml10", category: "most_likely", text: "Who is most likely to start a group chat argument?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml11", category: "most_likely", text: "Who is most likely to show up overdressed?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml12", category: "most_likely", text: "Who is most likely to show up underdressed?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml13", category: "most_likely", text: "Who is most likely to fall asleep at the party first?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml14", category: "most_likely", text: "Who is most likely to become a conspiracy theorist after one podcast?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml15", category: "most_likely", text: "Who is most likely to marry for the aesthetic?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml16", category: "most_likely", text: "Who is most likely to win a drinking contest and regret it?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml17", category: "most_likely", text: "Who is most likely to have a secret second Instagram?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml18", category: "most_likely", text: "Who is most likely to ask for the manager?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml19", category: "most_likely", text: "Who is most likely to move cities on a whim?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml20", category: "most_likely", text: "Who is most likely to become a wine parent?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml21", category: "most_likely", text: "Who is most likely to flirt with the bartender successfully?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml22", category: "most_likely", text: "Who is most likely to get caught in a lie tonight?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml23", category: "most_likely", text: "Who is most likely to start dancing with strangers?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml24", category: "most_likely", text: "Who is most likely to accidentally like an old photo while stalking?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml25", category: "most_likely", text: "Who is most likely to write a manifesto in the group chat at 2 a.m.?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml26", category: "most_likely", text: "Who is most likely to send a risky text they'll regret at brunch?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml27", category: "most_likely", text: "Who is most likely to get freaky in a bathroom at a party?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml28", category: "most_likely", text: "Who is most likely to suggest 'we should just make out' as conflict resolution?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml29", category: "most_likely", text: "Who is most likely to own the most interesting toy drawer?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml30", category: "most_likely", text: "Who is most likely to have a secret FWB right now?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml31", category: "most_likely", text: "Who is most likely to moan loud enough to wake the neighbors?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks." },
  { id: "ml32", category: "most_likely", text: "Who is most likely to initiate a strip-adjacent dare tonight?", hint: "Most Likely To — group points; that person drinks.", rule: "Point; that person drinks. Consent still rules." },
  { id: "cp01", category: "couples", text: "Couples: when did you know you wanted each other — not just officially? Singles: sip.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Partners high-five after answering." },
  { id: "cp02", category: "couples", text: "Couples: who initiates sex more? Point. That person drinks (proudly).", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles drink for freedom." },
  { id: "cp03", category: "couples", text: "Couples: describe your partner's sexiest non-obvious feature without using 'cute.'", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Partner drinks if unimpressed." },
  { id: "cp04", category: "couples", text: "Couples: who steals the blankets — and who steals the covers after sex? Guilty drinks.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: sip if you hog pillows." },
  { id: "cp05", category: "couples", text: "Couples: share your most ridiculous inside joke (spicy ones allowed).", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Everyone else drinks out of jealousy." },
  { id: "cp06", category: "couples", text: "Couples: who planned the last real date? The other drinks.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: drink if your last date was takeout + Netflix." },
  { id: "cp07", category: "couples", text: "Couples: stare into each other's eyes for 10 seconds like you want them. Laughers drink.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles pair up or sip twice." },
  { id: "cp08", category: "couples", text: "Couples: what's one filthy or fun thing you want to try together this year?", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Sip after sharing. Consent chat later." },
  { id: "cp09", category: "couples", text: "Couples: who has worse morning breath honesty hour? Loser drinks.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Be kind…-ish." },
  { id: "cp10", category: "couples", text: "Couples: finish this for your partner: 'I lose it when you…'", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Partner sips if they blush." },
  { id: "cp11", category: "couples", text: "Couples: who spends more money on the other? That person drinks (proudly).", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: sip for your wallet." },
  { id: "cp12", category: "couples", text: "Couples: recreate your first photo together pose — make it 10% hotter — or drink.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: pose solo & sip." },
  { id: "cp13", category: "couples", text: "Couples: what's a pet peeve in bed or mornings you've learned to live with?", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Partner drinks if they deny it." },
  { id: "cp14", category: "couples", text: "Couples: who would survive alone on a deserted island longer?", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Loser of the vote drinks." },
  { id: "cp15", category: "couples", text: "Couples: trade phones for 60 seconds — or both drink twice.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "No deleting. Don't open private albums without ask." },
  { id: "cp16", category: "couples", text: "Couples: kiss (lips or cheek — your call, both consent) in front of the group — or both sip.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Consent always. Refuse = drink." },
  { id: "cp17", category: "couples", text: "Couples: who falls asleep during movies more? That person drinks.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: drink if you snore." },
  { id: "cp18", category: "couples", text: "Couples: name three things on your shared bucket list — at least one spicy.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Miss one = both sip." },
  { id: "cp19", category: "couples", text: "Couples: who is messier at home? Group votes if disputed.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Messy one drinks." },
  { id: "cp20", category: "couples", text: "Couples: what's the best trip you've taken together — any hotel stories?", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Everyone else drinks to future trips." },
  { id: "cp21", category: "couples", text: "Couples: compliment your partner's body / outfit like it's the first night.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Sip after. Singles: compliment a friend kindly." },
  { id: "cp22", category: "couples", text: "Couples: who would forget the anniversary? Point & drink.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: drink if you've forgotten a birthday." },
  { id: "cp23", category: "couples", text: "Couples: what's your partner's biggest turn-on? Partner confirms or you drink.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Wrong = drink. Right = partner sips." },
  { id: "cp24", category: "couples", text: "Couples: who is louder? Point without talking. That person drinks.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Singles: sip if your neighbors know your business." },
  { id: "cp25", category: "couples", text: "Couples: share a safe word vibe check — do you have one? If not, invent a funny one now.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Both sip after. Singles invent one too." },
  { id: "cp26", category: "couples", text: "Couples: who wins 'most likely to start something on the couch during a movie'?", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Winner drinks. Singles: sip if guilty." },
  { id: "cp27", category: "couples", text: "Couples: whisper something dirty to your partner for 5 seconds — or both drink.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Keep volume private. Group only sees the blush." },
  { id: "cp28", category: "couples", text: "Couples: rate your sex life lately 1–10 together — average the scores.", hint: "Couples — partners answer / act; singles sip or join in.", rule: "Drink the gap from 10 (max 3). Singles rate their dry spell." },
  { id: "cp29", category: "couples", text: "Couples: who gives better massages that 'accidentally' escalate?", hint: "Couples — partners answer / act; singles sip or join in.", rule: "That person drinks. Demo optional & consensual." },
  { id: "fr01", category: "friends", text: "Who in this friend group knows the most secrets?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks." },
  { id: "fr02", category: "friends", text: "What's the funniest inside joke this group has?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Explain poorly; confused people drink." },
  { id: "fr03", category: "friends", text: "Who would bail you out of jail no questions asked?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks (loyalty tax)." },
  { id: "fr04", category: "friends", text: "Roast the person to your left in one sentence — kindly savage.", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "They drink if it's accurate." },
  { id: "fr05", category: "friends", text: "Who always suggests 'one more round'?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks." },
  { id: "fr06", category: "friends", text: "What's a friendship milestone you're proud of?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Group cheers; everyone sips." },
  { id: "fr07", category: "friends", text: "Who is most likely to start a group trip and forget the itinerary?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks." },
  { id: "fr08", category: "friends", text: "Share how you met the person across from you.", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "If you don't know: both drink." },
  { id: "fr09", category: "friends", text: "Who gives the best advice? Who gives the worst?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Both drink." },
  { id: "fr10", category: "friends", text: "What's a favor you've done for someone here that they forgot?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "They drink in apology." },
  { id: "fr11", category: "friends", text: "Who has the most chaotic energy in the group?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks." },
  { id: "fr12", category: "friends", text: "Name a trend this friend group started (or killed).", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Proud founders drink." },
  { id: "fr13", category: "friends", text: "Who would you call at 3 a.m.?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks." },
  { id: "fr14", category: "friends", text: "What's the dumbest argument this group has ever had?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Everyone who was involved sips." },
  { id: "fr15", category: "friends", text: "Who is the mom / dad friend? Crown them.", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "They drink for the unpaid labor." },
  { id: "fr16", category: "friends", text: "Compliment every person in the circle in three words or less.", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Skip someone = you drink." },
  { id: "fr17", category: "friends", text: "Who has changed the most since you became friends?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That person drinks (glow-up tax)." },
  { id: "fr18", category: "friends", text: "What's a tradition this group needs to start tonight?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Propose one or drink." },
  { id: "fr19", category: "friends", text: "Who always has snacks? Bless them — then they drink.", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Snack tax." },
  { id: "fr20", category: "friends", text: "If this group had a reality show title, what is it?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Best title wins; others drink." },
  { id: "fr21", category: "friends", text: "Who remembers birthdays without Facebook?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "That legend drinks." },
  { id: "fr22", category: "friends", text: "What's one thing you admire about the friend on your right?", hint: "Friends — roasting & loyalty; follow the drink rule.", rule: "Say it; they sip for the love." },
  { id: "w01", category: "wild_card", text: "Wild: the person holding the phone invents a rule for the next 3 cards.", hint: "Wild Card — anything goes. Host enforces.", rule: "Break it = drink." },
  { id: "w02", category: "wild_card", text: "Wild: everyone switches drinks with a neighbor for one sip. Cheers.", hint: "Wild Card — anything goes. Host enforces.", rule: "Allergies override — sip water." },
  { id: "w03", category: "wild_card", text: "Wild: last person to put their thumb on their nose drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Go!" },
  { id: "w04", category: "wild_card", text: "Wild: tell a 20-second scary story. Screams = storyteller drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Lights optional." },
  { id: "w05", category: "wild_card", text: "Wild: the group picks a celebrity; talk like them until next wild card — or drink twice.", hint: "Wild Card — anything goes. Host enforces.", rule: "Commit." },
  { id: "w06", category: "wild_card", text: "Wild: everyone must use a nickname for the person on their left for 5 minutes.", hint: "Wild Card — anything goes. Host enforces.", rule: "Real names = sip." },
  { id: "w07", category: "wild_card", text: "Wild: stack empty cups / cans. First knock-down drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Jenga energy." },
  { id: "w08", category: "wild_card", text: "Wild: host picks a word banned for 3 rounds. Say it = drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Choose wisely." },
  { id: "w09", category: "wild_card", text: "Wild: pass an ice cube / cold drink hand-to-hand. Dropper drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "No pockets." },
  { id: "w10", category: "wild_card", text: "Wild: everyone shares a hot take under 10 words. Weakest take drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Democracy." },
  { id: "w11", category: "wild_card", text: "Wild: play musical chairs with one fewer seat. Loser drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Music from someone's phone." },
  { id: "w12", category: "wild_card", text: "Wild: two truths and a lie — group votes. Wrong voters drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Liar drinks if caught… also if not." },
  { id: "w13", category: "wild_card", text: "Wild: everyone faces left. Last to spin drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Dizzy tax." },
  { id: "w14", category: "wild_card", text: "Wild: invent a cocktail name for someone here. Best name: others drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "No repeats." },
  { id: "w15", category: "wild_card", text: "Wild: the quietest person so far assigns drinks to two people.", hint: "Wild Card — anything goes. Host enforces.", rule: "Power move." },
  { id: "w16", category: "wild_card", text: "Wild: everyone with notifications on silent: drink. Loud phones: drink louder.", hint: "Wild Card — anything goes. Host enforces.", rule: "Balance." },
  { id: "w17", category: "wild_card", text: "Wild: mime your job for 15 seconds. Wrong guesses: guessers drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Actors sip if nobody gets it." },
  { id: "w18", category: "wild_card", text: "Wild: count to 20 as a group, alternating. Duplicate or skip = that person drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Focus." },
  { id: "w19", category: "wild_card", text: "Wild: draw a tattoo on someone's arm (pen). Artist and canvas drink after.", hint: "Wild Card — anything goes. Host enforces.", rule: "Consent first." },
  { id: "w20", category: "wild_card", text: "Wild: make the next toast in a different language — or finish your drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Gibberish allowed if committed." },
  { id: "w21", category: "wild_card", text: "Wild: everyone puts a shoe in the middle. Owner of the smelliest pair drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Nose jury." },
  { id: "w22", category: "wild_card", text: "Wild: the phone holder chooses a dance challenge. Refusers drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "10 seconds max." },
  { id: "w23", category: "wild_card", text: "Wild: share your most chaotic screenshot. Best chaos: others drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Blur secrets." },
  { id: "w24", category: "wild_card", text: "Wild: sudden compliment circle — each person compliments the next. Hesitators drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Spread the love." },
  { id: "w25", category: "wild_card", text: "Wild: for the next 3 cards, answers must include one spicy adjective — or sip.", hint: "Wild Card — anything goes. Host enforces.", rule: "Host enforces. Keep it adult, not cruel." },
  { id: "w26", category: "wild_card", text: "Wild: everyone who has ever sent a nude takes a sip. Solidarity optional.", hint: "Wild Card — anything goes. Host enforces.", rule: "No proof required. Honor system." },
  { id: "w27", category: "wild_card", text: "Wild: host assigns a consensual 'flirty seat swap' for one round — or those people drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Anyone can refuse = drink. No pressure." },
  { id: "w28", category: "wild_card", text: "Wild: two players (consenting) maintain knee-to-knee contact for one full card — or both drink.", hint: "Wild Card — anything goes. Host enforces.", rule: "Either can break = drink." },
  { id: "w29", category: "wild_card", text: "Wild: the group invents a safe-word for the party. Next person to say it drinks.", hint: "Wild Card — anything goes. Host enforces.", rule: "Also: respect if someone uses it for real." },
  { id: "tr01", category: "trivia", text: "{player}: In what year did the first iPhone launch?", answer: "2007", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr02", category: "trivia", text: "Which planet is known as the Red Planet?", answer: "Mars", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr03", category: "trivia", text: "{player}: What does \"www\" stand for in a website address?", answer: "World Wide Web", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr04", category: "trivia", text: "Which singer is known as the \"Queen of Pop\"?", answer: "Madonna", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr05", category: "trivia", text: "How many bones are in the adult human body?", answer: "206", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr06", category: "trivia", text: "{player}: What is the name of Harry Potter's pet owl?", answer: "Hedwig", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr07", category: "trivia", text: "Which fast-food chain uses a clown as its mascot?", answer: "McDonald's (Ronald McDonald)", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr08", category: "trivia", text: "In Friends, what is the name of Ross and Monica's last name?", answer: "Geller", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr09", category: "trivia", text: "{player}: What's the chemical formula for water?", answer: "H₂O", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr10", category: "trivia", text: "Which pop star released the album Midnights in 2022?", answer: "Taylor Swift", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr11", category: "trivia", text: "What's the only mammal capable of true flight?", answer: "Bats", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr12", category: "trivia", text: "{player}: In Mean Girls, what day is it on Wednesdays?", answer: "Wear pink", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr13", category: "trivia", text: "How many minutes are in a full week?", answer: "10,080", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr14", category: "trivia", text: "Which fruit is on the Apple logo?", answer: "An apple (with a bite taken out)", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr15", category: "trivia", text: "{player}: What does GIF originally stand for?", answer: "Graphics Interchange Format", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr16", category: "trivia", text: "Which ocean is the largest?", answer: "Pacific Ocean", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr17", category: "trivia", text: "In The Office (US), what is Dwight's last name?", answer: "Schrute", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr18", category: "trivia", text: "{player}: How many hearts does an octopus have?", answer: "Three", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr19", category: "trivia", text: "What year did TikTok launch globally (as TikTok)?", answer: "2018 (international launch)", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr20", category: "trivia", text: "Which spice is the world's most expensive by weight?", answer: "Saffron", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr21", category: "trivia", text: "{player}: What's the name of the coffee shop in Friends?", answer: "Central Perk", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr22", category: "trivia", text: "A group of flamingos is called what?", answer: "A flamboyance", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr23", category: "trivia", text: "Which Marvel movie kicked off the MCU?", answer: "Iron Man (2008)", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr24", category: "trivia", text: "{player}: What's the capital of Australia?", answer: "Canberra (not Sydney!)", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr25", category: "trivia", text: "How many strings does a standard guitar have?", answer: "Six", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr26", category: "trivia", text: "What does \"selfie\" literally refer to?", answer: "A photo you take of yourself", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr27", category: "trivia", text: "{player}: In Monopoly, how much is Boardwalk?", answer: "$400", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "tr28", category: "trivia", text: "Weird fact: what's the national animal of Scotland?", answer: "The unicorn", hint: "Trivia — guess first, then tap to reveal. Drink if wrong, sip if right.", rule: "Drink if wrong. Sip if right." },
  { id: "wr01", category: "would_you_rather", text: "{player}: Would you rather never use social media again, or never eat your favorite food again?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr02", category: "would_you_rather", text: "Would you rather always say everything on your mind, or never speak again?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr03", category: "would_you_rather", text: "Would you rather have a pause button for life, or a rewind button (once a day)?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr04", category: "would_you_rather", text: "{player}: Would you rather be 10 minutes late forever, or 20 minutes early forever?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr05", category: "would_you_rather", text: "Would you rather date someone who never texts back, or someone who texts too much?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr06", category: "would_you_rather", text: "Would you rather accidentally like your ex's 3-year-old photo, or send a spicy text to your boss?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr07", category: "would_you_rather", text: "{player}: Would you rather only whisper, or only shout, for a week?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr08", category: "would_you_rather", text: "Would you rather have your search history leaked, or your camera roll leaked?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr09", category: "would_you_rather", text: "Would you rather be famous for something embarrassing, or never be known at all?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr10", category: "would_you_rather", text: "{player}: Would you rather always have to sing instead of talk, or dance instead of walk?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr11", category: "would_you_rather", text: "Would you rather lose your phone for a month, or your wallet for a week?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr12", category: "would_you_rather", text: "Would you rather have an awkward first kiss on live TV, or an awkward wedding speech go viral?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr13", category: "would_you_rather", text: "Would you rather always know when someone is lying, or never be able to lie yourself?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr14", category: "would_you_rather", text: "{player}: Would you rather fight one horse-sized duck, or 100 duck-sized horses?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr15", category: "would_you_rather", text: "Would you rather have unlimited takeout for a year, or a free dream vacation every year forever?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr16", category: "would_you_rather", text: "Would you rather your parents see your DMs, or your coworkers see your camera roll?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr17", category: "would_you_rather", text: "{player}: Would you rather be stuck in an elevator with your crush, or your ex?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr18", category: "would_you_rather", text: "Would you rather only eat spicy food forever, or never taste spice again?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr19", category: "would_you_rather", text: "Would you rather have a personal hype-person follow you around, or a brutally honest critic?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr20", category: "would_you_rather", text: "Would you rather wake up every day at 5am happy, or sleep till noon but always feel groggy?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr21", category: "would_you_rather", text: "{player}: Would you rather accidentally call your teacher \"mom,\" or your partner by an ex's name?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr22", category: "would_you_rather", text: "Would you rather have perfect hair every day, or perfect skin every day?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "wr23", category: "would_you_rather", text: "Would you rather live without AC in summer, or without heat in winter?", hint: "Would You Rather — group picks a side. Minority drinks (or loser of a vote).", rule: "Minority drinks. Tie = everyone sips." },
  { id: "ib01", category: "icebreaker", text: "{player}: What's a hobby you'd love to brag about more — even if it's weirdly specific?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after sharing. Pass = two sips." },
  { id: "ib02", category: "icebreaker", text: "Go around: everyone shares their current drink order and why it matches their personality.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after sharing." },
  { id: "ib03", category: "icebreaker", text: "{player}: What was your first concert — or the dream one you'd invent if you never went?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after sharing. Pass = two sips." },
  { id: "ib04", category: "icebreaker", text: "What's a comfort movie you can quote without shame?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Everyone who relates sips." },
  { id: "ib05", category: "icebreaker", text: "{player}: Two truths about your childhood (keep them fun, not trauma-dumping).", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Group picks a favorite; you sip either way." },
  { id: "ib06", category: "icebreaker", text: "If this night had a soundtrack song, what is it — main character edition?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Best pick: others sip." },
  { id: "ib07", category: "icebreaker", text: "{player}: What's your go-to karaoke or shower song when nobody's supposed to hear?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Hum a line or drink." },
  { id: "ib08", category: "icebreaker", text: "Name a food you'd travel across town for at 1 a.m.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after sharing." },
  { id: "ib09", category: "icebreaker", text: "{player}: What's a small win from this week that deserves a toast?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Group cheers; everyone sips." },
  { id: "ib10", category: "icebreaker", text: "Who here have you known the longest? Tell a 10-second origin story with one roast.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Storyteller sips; friends cheer." },
  { id: "ib11", category: "icebreaker", text: "{player}: Beach vacation, cabin trip, or city weekend — pick one and defend it like a lawyer.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Dissenters sip." },
  { id: "ib12", category: "icebreaker", text: "What's a skill you're secretly proud of that never makes LinkedIn?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Demo or sip twice." },
  { id: "ib13", category: "icebreaker", text: "{player}: Introduce the person on your right like they're a chaotic celebrity.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Keep it kind. Both sip after." },
  { id: "ib14", category: "icebreaker", text: "What emoji is your personality today — no corporate smile allowed?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Everyone shows; then sip." },
  { id: "ib15", category: "icebreaker", text: "{player}: What's the best piece of advice you've actually used (not just screenshotted)?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after sharing." },
  { id: "ib16", category: "icebreaker", text: "High-five your neighbor, then share one thing you're excited about tonight.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after the high-five round." },
  { id: "ib17", category: "icebreaker", text: "{player}: Dogs, cats, or chaotic third option (explain the chaos)?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Minority animal camp drinks." },
  { id: "ib18", category: "icebreaker", text: "What's a TV show you'd rewatch from scratch with this group?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Agreement sip." },
  { id: "ib19", category: "icebreaker", text: "{player}: Teach the group a 5-second dance move or toast ritual.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Everyone copies once, then sips." },
  { id: "ib20", category: "icebreaker", text: "What's your unofficial job title in friend groups (planner, comic, snack boss, chaos gremlin…)?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Own it, then sip." },
  { id: "ib21", category: "icebreaker", text: "{player}: Share a travel story in under 20 seconds — plot twist required.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Timer optional; sip after." },
  { id: "ib22", category: "icebreaker", text: "Compliment circle lite: say one nice (or funny-nice) thing about the vibe tonight.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Everyone shares; everyone sips." },
  { id: "ib23", category: "icebreaker", text: "{player}: What's your coffee / tea / energy-drink order — roast yourself if needed?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip for the caffeine loyalty." },
  { id: "ib24", category: "icebreaker", text: "If you could instantly learn one party skill, what would it be?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Sip after sharing." },
  { id: "ib25", category: "icebreaker", text: "{player}: What's the funniest autocorrect fail you've sent in a group chat?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Share or sip twice." },
  { id: "ib26", category: "icebreaker", text: "Who here has the most chaotic morning routine? Defend your nominee.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "That person drinks." },
  { id: "ib27", category: "icebreaker", text: "{player}: Invent a ridiculous reality-show title for your life right now.", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Best title: others sip." },
  { id: "ib28", category: "icebreaker", text: "What's a hill you'll die on that's completely unimportant?", hint: "Icebreaker — warm, low-pressure share. Sip after answering.", rule: "Defend or drink." }
];

window.SIP_GENRES = {
  "all": {
    "id": "all",
    "label": "All",
    "blurb": "Every prompt in the deck. Shuffle & sip."
  },
  "mild": {
    "id": "mild",
    "label": "Mild",
    "blurb": "Witty PG-13 truths, absurd roasts, low-stakes comedy. Still milder heat."
  },
  "spicy": {
    "id": "spicy",
    "label": "Spicy",
    "blurb": "Explicit adult-party questions — dirty, NSFW, consensual vibe."
  },
  "chaos": {
    "id": "chaos",
    "label": "Chaos",
    "blurb": "Dares, group rules, physical silliness. Obey or drink."
  },
  "sexy_truth": {
    "id": "sexy_truth",
    "label": "Sexy Truth",
    "blurb": "Filthy steamy questions. Answer honestly or sip to pass."
  },
  "sexy_dare": {
    "id": "sexy_dare",
    "label": "Sexy Dare",
    "blurb": "Flirty/NSFW dares — consent first, refuse = drink."
  },
  "never_have_i_ever": {
    "id": "never_have_i_ever",
    "label": "Never Have I Ever",
    "blurb": "Drink if you HAVE done it. Pass = stay dry."
  },
  "most_likely": {
    "id": "most_likely",
    "label": "Most Likely To",
    "blurb": "Group points at who fits. That person drinks."
  },
  "couples": {
    "id": "couples",
    "label": "Couples",
    "blurb": "Partner prompts (including spicy). Singles sip or pair up."
  },
  "friends": {
    "id": "friends",
    "label": "Friends",
    "blurb": "Loyalty, roasts, and group lore. Friendship tax applies."
  },
  "wild_card": {
    "id": "wild_card",
    "label": "Wild Card",
    "blurb": "Unpredictable house rules (some spicy). Host keeps the peace."
  },
  "trivia": {
    "id": "trivia",
    "label": "Trivia",
    "blurb": "Party trivia — guess, tap to reveal. Drink if wrong, sip if right."
  },
  "would_you_rather": {
    "id": "would_you_rather",
    "label": "Would You Rather",
    "blurb": "Two spicy/funny options. Group picks; minority (or loser) drinks."
  },
  "icebreaker": {
    "id": "icebreaker",
    "label": "Icebreaker",
    "blurb": "Warm, funny starter prompts for mixed groups. Easy shares, light sips."
  }
};
